export { default as Main } from "./Main"
export { default as Home } from "./Home"
export { default as Login} from "./Login"
export { default as NavBar } from "./NavBar"
export { default as Posts } from "./Posts"
export { default as Register } from "./Register"