export { default as Main } from "./Main"
export { default as CreatePosts } from "./CreatePosts"
export { default as CreateMessage } from "./CreateMessage"
export { default as Home } from "./Home"
export { default as Login} from "./Login"
export { default as NavBar } from "./NavBar"
export { default as Posts } from "./Posts"
export { default as Profile } from "./Profile"
export { default as Register } from "./Register"